"""radiology studies and triage

De-identified DICOM studies, the triage model's output (kept in ml_predictions like every other model)
and the radiologist's report. medical_records.record_type gains "radiology_report"; the enum is a CHECK
constraint rather than a native type, so it is dropped and recreated.

Revision ID: 2f55f2cf3e64
Revises: 9a4c2e7f1b58
Create Date: 2026-09-22 13:29:30.636704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f55f2cf3e64'
down_revision: Union[str, Sequence[str], None] = '9a4c2e7f1b58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imaging_studies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('admission_id', sa.Integer(), nullable=True),
    sa.Column('accession', sa.String(length=24), nullable=False),
    sa.Column('study_uid', sa.String(length=80), nullable=False),
    sa.Column('series_uid', sa.String(length=80), nullable=False),
    sa.Column('sop_uid', sa.String(length=80), nullable=False),
    sa.Column('modality', sa.String(length=8), nullable=False),
    sa.Column('body_part', sa.String(length=32), nullable=True),
    sa.Column('view_position', sa.String(length=8), nullable=True),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('indication', sa.String(length=256), nullable=True),
    sa.Column('rows', sa.Integer(), nullable=False),
    sa.Column('columns', sa.Integer(), nullable=False),
    sa.Column('bits_stored', sa.Integer(), nullable=False),
    sa.Column('window_center', sa.Float(), nullable=False),
    sa.Column('window_width', sa.Float(), nullable=False),
    sa.Column('acquired_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('storage_path', sa.String(length=512), nullable=False),
    sa.Column('file_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('deidentification', sa.JSON(), nullable=False),
    sa.Column('uploaded_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('triage_prediction_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['admission_id'], ['admissions.id'], name=op.f('fk_imaging_studies_admission_id_admissions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_imaging_studies_patient_id_patients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['triage_prediction_id'], ['ml_predictions.id'], name=op.f('fk_imaging_studies_triage_prediction_id_ml_predictions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], name=op.f('fk_imaging_studies_uploaded_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_imaging_studies')),
    sa.UniqueConstraint('accession', name=op.f('uq_imaging_studies_accession')),
    sa.UniqueConstraint('study_uid', name=op.f('uq_imaging_studies_study_uid'))
    )
    op.create_index('ix_imaging_studies_patient_acquired', 'imaging_studies', ['patient_id', 'acquired_at'], unique=False)
    op.create_table('imaging_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('study_id', sa.Integer(), nullable=False),
    sa.Column('findings', sa.Text(), nullable=False),
    sa.Column('impression', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'final', name='imaging_report_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('model_agreement', sa.Enum('agreed', 'partly', 'disagreed', 'not_used', name='imaging_model_agreement', native_enum=False, create_constraint=True, length=32), nullable=True),
    sa.Column('model_snapshot', sa.JSON(), nullable=False),
    sa.Column('reported_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('record_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['record_id'], ['medical_records.id'], name=op.f('fk_imaging_reports_record_id_medical_records'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reported_by_user_id'], ['users.id'], name=op.f('fk_imaging_reports_reported_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['study_id'], ['imaging_studies.id'], name=op.f('fk_imaging_reports_study_id_imaging_studies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_imaging_reports')),
    sa.UniqueConstraint('study_id', name=op.f('uq_imaging_reports_study_id'))
    )
    # ### end Alembic commands ###
    op.drop_constraint('record_type', 'medical_records', type_='check')
    op.create_check_constraint(
        'record_type', 'medical_records',
        "record_type IN ('consultation', 'progress_note', 'discharge_summary', 'radiology_report', "
        "'emergency', 'follow_up')")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM medical_records WHERE record_type = 'radiology_report'")
    op.drop_constraint('record_type', 'medical_records', type_='check')
    op.create_check_constraint(
        'record_type', 'medical_records',
        "record_type IN ('consultation', 'progress_note', 'discharge_summary', 'emergency', 'follow_up')")
    op.drop_table('imaging_reports')
    op.drop_index('ix_imaging_studies_patient_acquired', table_name='imaging_studies')
    op.drop_table('imaging_studies')
    # ### end Alembic commands ###
