"""initial schema

Revision ID: 755f39ee55d1
Revises: 
Create Date: 2026-09-11 16:02:14.210546

"""
from typing import Sequence, Union

from alembic import op
import pgvector.sqlalchemy
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '755f39ee55d1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_departments')),
    sa.UniqueConstraint('code', name=op.f('uq_departments_code')),
    sa.UniqueConstraint('name', name=op.f('uq_departments_name'))
    )
    op.create_table('medications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('drug_class', sa.String(length=64), nullable=False),
    sa.Column('is_high_alert', sa.Boolean(), nullable=False),
    sa.Column('default_route', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_medications')),
    sa.UniqueConstraint('name', name=op.f('uq_medications_name'))
    )
    op.create_index(op.f('ix_medications_drug_class'), 'medications', ['drug_class'], unique=False)
    op.create_table('model_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('task', sa.String(length=32), nullable=False),
    sa.Column('algorithm', sa.String(length=64), nullable=False),
    sa.Column('trained_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('dataset_name', sa.String(length=128), nullable=False),
    sa.Column('dataset_version', sa.String(length=64), nullable=False),
    sa.Column('feature_config', sa.JSON(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('artifact_path', sa.String(length=512), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_versions')),
    sa.UniqueConstraint('model_name', 'version', name=op.f('uq_model_versions_model_name'))
    )
    op.create_index(op.f('ix_model_versions_model_name'), 'model_versions', ['model_name'], unique=False)
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions')),
    sa.UniqueConstraint('code', name=op.f('uq_permissions_code'))
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('name', name=op.f('uq_roles_name'))
    )
    op.create_table('doctors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staff_code', sa.String(length=16), nullable=False),
    sa.Column('full_name', sa.String(length=128), nullable=False),
    sa.Column('specialty', sa.String(length=64), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('availability', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_doctors_department_id_departments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_doctors')),
    sa.UniqueConstraint('staff_code', name=op.f('uq_doctors_staff_code'))
    )
    op.create_index(op.f('ix_doctors_department_id'), 'doctors', ['department_id'], unique=False)
    op.create_index(op.f('ix_doctors_full_name'), 'doctors', ['full_name'], unique=False)
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mrn', sa.String(length=16), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('sex', sa.Enum('F', 'M', 'X', name='sex', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('preferred_language', sa.String(length=32), nullable=False),
    sa.Column('blood_type', sa.String(length=4), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=128), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=32), nullable=True),
    sa.Column('emergency_contact_relation', sa.String(length=32), nullable=True),
    sa.Column('allergies', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('active', 'admitted', 'discharged', 'inactive', 'deceased', name='patient_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('primary_department_id', sa.Integer(), nullable=True),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['primary_department_id'], ['departments.id'], name=op.f('fk_patients_primary_department_id_departments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_patients')),
    sa.UniqueConstraint('mrn', name=op.f('uq_patients_mrn'))
    )
    op.create_index(op.f('ix_patients_last_name'), 'patients', ['last_name'], unique=False)
    op.create_index(op.f('ix_patients_primary_department_id'), 'patients', ['primary_department_id'], unique=False)
    op.create_index(op.f('ix_patients_status'), 'patients', ['status'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('fk_role_permissions_permission_id_permissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_role_permissions_role_id_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id', name=op.f('pk_role_permissions'))
    )
    op.create_table('admissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('attending_doctor_id', sa.Integer(), nullable=True),
    sa.Column('admitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('discharged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('admission_type', sa.Enum('emergency', 'urgent', 'elective', name='admission_type', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('admission_source', sa.Enum('emergency_room', 'physician_referral', 'transfer', 'clinic', name='admission_source', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('discharge_disposition', sa.Enum('home', 'home_health', 'skilled_nursing', 'rehab', 'transfer', 'ama', 'expired', name='discharge_disposition', native_enum=False, create_constraint=True, length=32), nullable=True),
    sa.Column('status', sa.Enum('admitted', 'discharged', name='admission_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('ward', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status = 'admitted' AND discharged_at IS NULL) OR (status = 'discharged' AND discharged_at IS NOT NULL)", name=op.f('ck_admissions_status_matches_discharge')),
    sa.CheckConstraint('discharged_at IS NULL OR discharged_at >= admitted_at', name=op.f('ck_admissions_discharge_after_admit')),
    sa.ForeignKeyConstraint(['attending_doctor_id'], ['doctors.id'], name=op.f('fk_admissions_attending_doctor_id_doctors')),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_admissions_department_id_departments')),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_admissions_patient_id_patients'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admissions'))
    )
    op.create_index(op.f('ix_admissions_attending_doctor_id'), 'admissions', ['attending_doctor_id'], unique=False)
    op.create_index(op.f('ix_admissions_department_id'), 'admissions', ['department_id'], unique=False)
    op.create_index('ix_admissions_patient_admitted', 'admissions', ['patient_id', 'admitted_at'], unique=False)
    op.create_index(op.f('ix_admissions_status'), 'admissions', ['status'], unique=False)
    op.create_table('patient_embeddings',
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('representation_version', sa.String(length=32), nullable=False),
    sa.Column('vector', pgvector.sqlalchemy.vector.VECTOR(dim=32), nullable=False),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_patient_embeddings_patient_id_patients'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('patient_id', name=op.f('pk_patient_embeddings'))
    )
    op.create_index('ix_patient_embeddings_vector_hnsw', 'patient_embeddings', ['vector'], unique=False, postgresql_using='hnsw', postgresql_ops={'vector': 'vector_cosine_ops'})
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=128), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_users_department_id_departments')),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], name=op.f('fk_users_doctor_id_doctors')),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_users_role_id_roles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('doctor_id', name=op.f('uq_users_doctor_id'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
    op.create_table('ai_query_traces',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('query_hash', sa.String(length=64), nullable=False),
    sa.Column('query_length', sa.Integer(), nullable=False),
    sa.Column('route', sa.String(length=64), nullable=False),
    sa.Column('routing_method', sa.String(length=16), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('llm_model', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('total_ms', sa.Float(), nullable=False),
    sa.Column('stage_ms', sa.JSON(), nullable=False),
    sa.Column('retrieved_chunk_ids', sa.JSON(), nullable=False),
    sa.Column('cited_source_ids', sa.JSON(), nullable=False),
    sa.Column('tool_calls', sa.JSON(), nullable=False),
    sa.Column('model_versions', sa.JSON(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ai_query_traces_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_query_traces'))
    )
    op.create_index(op.f('ix_ai_query_traces_created_at'), 'ai_query_traces', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_query_traces_route'), 'ai_query_traces', ['route'], unique=False)
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('appointment_type', sa.Enum('outpatient', 'follow_up', 'emergency', 'telehealth', name='appointment_type', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('scheduled', 'checked_in', 'completed', 'cancelled', 'no_show', name='appointment_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('cancellation_reason', sa.String(length=255), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('duration_minutes BETWEEN 5 AND 240', name=op.f('ck_appointments_duration_range')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_appointments_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_appointments_department_id_departments')),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], name=op.f('fk_appointments_doctor_id_doctors')),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_appointments_patient_id_patients'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_appointments'))
    )
    op.create_index(op.f('ix_appointments_department_id'), 'appointments', ['department_id'], unique=False)
    op.create_index('ix_appointments_doctor_start', 'appointments', ['doctor_id', 'scheduled_start'], unique=False)
    op.create_index(op.f('ix_appointments_patient_id'), 'appointments', ['patient_id'], unique=False)
    op.create_index(op.f('ix_appointments_status'), 'appointments', ['status'], unique=False)
    op.create_index('uq_appointments_doctor_slot', 'appointments', ['doctor_id', 'scheduled_start'], unique=True, postgresql_where=sa.text("status IN ('scheduled', 'checked_in')"))
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_role', sa.String(length=32), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=32), nullable=True),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_occurred_at'), 'audit_logs', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_patient_id'), 'audit_logs', ['patient_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('care_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('care_role', sa.Enum('attending', 'consulting', 'nurse', name='care_role', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_care_assignments_patient_id_patients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_care_assignments_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_care_assignments')),
    sa.UniqueConstraint('patient_id', 'user_id', name=op.f('uq_care_assignments_patient_id'))
    )
    op.create_index(op.f('ix_care_assignments_patient_id'), 'care_assignments', ['patient_id'], unique=False)
    op.create_index(op.f('ix_care_assignments_user_id'), 'care_assignments', ['user_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doc_key', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('storage_path', sa.String(length=512), nullable=False),
    sa.Column('doc_type', sa.Enum('guideline', 'policy', 'protocol', 'procedure', 'report', 'other', name='doc_type', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('access_scope', sa.Enum('all_staff', 'clinical', 'admin', name='access_scope', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('uploading', 'processing', 'indexed', 'failed', name='doc_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('error_message', sa.String(length=512), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('flagged_chunk_count', sa.Integer(), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('uploaded_by_user_id', sa.Integer(), nullable=True),
    sa.Column('indexed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_documents_department_id_departments')),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_documents_patient_id_patients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], name=op.f('fk_documents_uploaded_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents')),
    sa.UniqueConstraint('doc_key', 'version', name=op.f('uq_documents_doc_key'))
    )
    op.create_index(op.f('ix_documents_access_scope'), 'documents', ['access_scope'], unique=False)
    op.create_index(op.f('ix_documents_department_id'), 'documents', ['department_id'], unique=False)
    op.create_index(op.f('ix_documents_doc_key'), 'documents', ['doc_key'], unique=False)
    op.create_index(op.f('ix_documents_is_current'), 'documents', ['is_current'], unique=False)
    op.create_index(op.f('ix_documents_patient_id'), 'documents', ['patient_id'], unique=False)
    op.create_index(op.f('ix_documents_status'), 'documents', ['status'], unique=False)
    op.create_table('medical_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('admission_id', sa.Integer(), nullable=True),
    sa.Column('visit_date', sa.Date(), nullable=False),
    sa.Column('record_type', sa.Enum('consultation', 'progress_note', 'discharge_summary', 'emergency', 'follow_up', name='record_type', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('chief_complaint', sa.String(length=255), nullable=False),
    sa.Column('symptoms', sa.Text(), nullable=True),
    sa.Column('diagnosis_summary', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('treatment_plan', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admission_id'], ['admissions.id'], name=op.f('fk_medical_records_admission_id_admissions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], name=op.f('fk_medical_records_doctor_id_doctors')),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_medical_records_patient_id_patients'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_medical_records'))
    )
    op.create_index('ix_medical_records_patient_visit', 'medical_records', ['patient_id', 'visit_date'], unique=False)
    op.create_table('ml_predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_version_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('admission_id', sa.Integer(), nullable=True),
    sa.Column('requested_by_user_id', sa.Integer(), nullable=True),
    sa.Column('prediction_type', sa.String(length=32), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('label', sa.String(length=32), nullable=True),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('explanation', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admission_id'], ['admissions.id'], name=op.f('fk_ml_predictions_admission_id_admissions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], name=op.f('fk_ml_predictions_model_version_id_model_versions')),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_ml_predictions_patient_id_patients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], name=op.f('fk_ml_predictions_requested_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ml_predictions'))
    )
    op.create_index(op.f('ix_ml_predictions_model_version_id'), 'ml_predictions', ['model_version_id'], unique=False)
    op.create_index('ix_ml_predictions_patient_created', 'ml_predictions', ['patient_id', 'created_at'], unique=False)
    op.create_table('prescriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('medication_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('admission_id', sa.Integer(), nullable=True),
    sa.Column('dosage', sa.String(length=64), nullable=False),
    sa.Column('frequency', sa.String(length=64), nullable=False),
    sa.Column('route', sa.String(length=16), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('active', 'completed', 'discontinued', name='prescription_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('change_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('duration_days IS NULL OR duration_days > 0', name=op.f('ck_prescriptions_positive_duration')),
    sa.CheckConstraint('end_date IS NULL OR end_date >= start_date', name=op.f('ck_prescriptions_end_after_start')),
    sa.ForeignKeyConstraint(['admission_id'], ['admissions.id'], name=op.f('fk_prescriptions_admission_id_admissions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], name=op.f('fk_prescriptions_doctor_id_doctors')),
    sa.ForeignKeyConstraint(['medication_id'], ['medications.id'], name=op.f('fk_prescriptions_medication_id_medications')),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_prescriptions_patient_id_patients'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prescriptions'))
    )
    op.create_index(op.f('ix_prescriptions_medication_id'), 'prescriptions', ['medication_id'], unique=False)
    op.create_index('ix_prescriptions_patient_start', 'prescriptions', ['patient_id', 'start_date'], unique=False)
    op.create_index(op.f('ix_prescriptions_status'), 'prescriptions', ['status'], unique=False)
    op.create_table('diagnoses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('medical_record_id', sa.Integer(), nullable=True),
    sa.Column('admission_id', sa.Integer(), nullable=True),
    sa.Column('icd10_code', sa.String(length=10), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('category', sa.Enum('circulatory', 'respiratory', 'digestive', 'diabetes', 'injury', 'musculoskeletal', 'genitourinary', 'neoplasms', 'other', name='diagnosis_category', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('is_chronic', sa.Boolean(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('active', 'resolved', name='diagnosis_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('diagnosed_on', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admission_id'], ['admissions.id'], name=op.f('fk_diagnoses_admission_id_admissions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['medical_record_id'], ['medical_records.id'], name=op.f('fk_diagnoses_medical_record_id_medical_records'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_diagnoses_patient_id_patients'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_diagnoses'))
    )
    op.create_index(op.f('ix_diagnoses_icd10_code'), 'diagnoses', ['icd10_code'], unique=False)
    op.create_index(op.f('ix_diagnoses_patient_id'), 'diagnoses', ['patient_id'], unique=False)
    op.create_table('document_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('section_path', sa.String(length=512), nullable=False),
    sa.Column('page_start', sa.Integer(), nullable=True),
    sa.Column('page_end', sa.Integer(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False),
    sa.Column('flags', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_document_chunks_document_id_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_chunks')),
    sa.UniqueConstraint('document_id', 'chunk_index', name=op.f('uq_document_chunks_document_id'))
    )
    op.create_index(op.f('ix_document_chunks_content_hash'), 'document_chunks', ['content_hash'], unique=False)
    op.create_index(op.f('ix_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    op.create_index('ix_document_chunks_embedding_hnsw', 'document_chunks', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_table('lab_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('admission_id', sa.Integer(), nullable=True),
    sa.Column('ordered_by_doctor_id', sa.Integer(), nullable=True),
    sa.Column('test_code', sa.String(length=16), nullable=False),
    sa.Column('test_name', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('value_text', sa.String(length=128), nullable=True),
    sa.Column('unit', sa.String(length=16), nullable=True),
    sa.Column('reference_low', sa.Float(), nullable=True),
    sa.Column('reference_high', sa.Float(), nullable=True),
    sa.Column('flag', sa.Enum('normal', 'low', 'high', 'critical', name='lab_flag', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reported_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admission_id'], ['admissions.id'], name=op.f('fk_lab_reports_admission_id_admissions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_lab_reports_document_id_documents'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ordered_by_doctor_id'], ['doctors.id'], name=op.f('fk_lab_reports_ordered_by_doctor_id_doctors')),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_lab_reports_patient_id_patients'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lab_reports'))
    )
    op.create_index('ix_lab_reports_patient_collected', 'lab_reports', ['patient_id', 'collected_at'], unique=False)
    op.create_index(op.f('ix_lab_reports_test_code'), 'lab_reports', ['test_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lab_reports_test_code'), table_name='lab_reports')
    op.drop_index('ix_lab_reports_patient_collected', table_name='lab_reports')
    op.drop_table('lab_reports')
    op.drop_index('ix_document_chunks_embedding_hnsw', table_name='document_chunks', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index(op.f('ix_document_chunks_document_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_content_hash'), table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_diagnoses_patient_id'), table_name='diagnoses')
    op.drop_index(op.f('ix_diagnoses_icd10_code'), table_name='diagnoses')
    op.drop_table('diagnoses')
    op.drop_index(op.f('ix_prescriptions_status'), table_name='prescriptions')
    op.drop_index('ix_prescriptions_patient_start', table_name='prescriptions')
    op.drop_index(op.f('ix_prescriptions_medication_id'), table_name='prescriptions')
    op.drop_table('prescriptions')
    op.drop_index('ix_ml_predictions_patient_created', table_name='ml_predictions')
    op.drop_index(op.f('ix_ml_predictions_model_version_id'), table_name='ml_predictions')
    op.drop_table('ml_predictions')
    op.drop_index('ix_medical_records_patient_visit', table_name='medical_records')
    op.drop_table('medical_records')
    op.drop_index(op.f('ix_documents_status'), table_name='documents')
    op.drop_index(op.f('ix_documents_patient_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_is_current'), table_name='documents')
    op.drop_index(op.f('ix_documents_doc_key'), table_name='documents')
    op.drop_index(op.f('ix_documents_department_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_access_scope'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_care_assignments_user_id'), table_name='care_assignments')
    op.drop_index(op.f('ix_care_assignments_patient_id'), table_name='care_assignments')
    op.drop_table('care_assignments')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_patient_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_occurred_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('uq_appointments_doctor_slot', table_name='appointments', postgresql_where=sa.text("status IN ('scheduled', 'checked_in')"))
    op.drop_index(op.f('ix_appointments_status'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_patient_id'), table_name='appointments')
    op.drop_index('ix_appointments_doctor_start', table_name='appointments')
    op.drop_index(op.f('ix_appointments_department_id'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_ai_query_traces_route'), table_name='ai_query_traces')
    op.drop_index(op.f('ix_ai_query_traces_created_at'), table_name='ai_query_traces')
    op.drop_table('ai_query_traces')
    op.drop_index(op.f('ix_users_role_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_patient_embeddings_vector_hnsw', table_name='patient_embeddings', postgresql_using='hnsw', postgresql_ops={'vector': 'vector_cosine_ops'})
    op.drop_table('patient_embeddings')
    op.drop_index(op.f('ix_admissions_status'), table_name='admissions')
    op.drop_index('ix_admissions_patient_admitted', table_name='admissions')
    op.drop_index(op.f('ix_admissions_department_id'), table_name='admissions')
    op.drop_index(op.f('ix_admissions_attending_doctor_id'), table_name='admissions')
    op.drop_table('admissions')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_patients_status'), table_name='patients')
    op.drop_index(op.f('ix_patients_primary_department_id'), table_name='patients')
    op.drop_index(op.f('ix_patients_last_name'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_doctors_full_name'), table_name='doctors')
    op.drop_index(op.f('ix_doctors_department_id'), table_name='doctors')
    op.drop_table('doctors')
    op.drop_table('roles')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_model_versions_model_name'), table_name='model_versions')
    op.drop_table('model_versions')
    op.drop_index(op.f('ix_medications_drug_class'), table_name='medications')
    op.drop_table('medications')
    op.drop_table('departments')
    # ### end Alembic commands ###
