"""vital signs and NEWS2

Revision ID: 9a4c2e7f1b58
Revises: 7d2f0b6a9c31
Create Date: 2026-09-18 20:00:44.763984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a4c2e7f1b58'
down_revision: Union[str, Sequence[str], None] = '7d2f0b6a9c31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vital_signs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('admission_id', sa.Integer(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recorded_by_user_id', sa.Integer(), nullable=True),
    sa.Column('respiratory_rate', sa.Integer(), nullable=False),
    sa.Column('spo2', sa.Integer(), nullable=False),
    sa.Column('spo2_scale', sa.SmallInteger(), nullable=False),
    sa.Column('on_oxygen', sa.Boolean(), nullable=False),
    sa.Column('systolic_bp', sa.Integer(), nullable=False),
    sa.Column('diastolic_bp', sa.Integer(), nullable=True),
    sa.Column('heart_rate', sa.Integer(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('consciousness', sa.Enum('A', 'C', 'V', 'P', 'U', name='consciousness_level', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('news2_score', sa.Integer(), nullable=False),
    sa.Column('news2_risk', sa.Enum('low', 'low_medium', 'medium', 'high', name='news2_risk', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.CheckConstraint('diastolic_bp IS NULL OR diastolic_bp BETWEEN 20 AND 200', name=op.f('ck_vital_signs_dbp_range')),
    sa.CheckConstraint('heart_rate BETWEEN 20 AND 250', name=op.f('ck_vital_signs_hr_range')),
    sa.CheckConstraint('news2_score BETWEEN 0 AND 20', name=op.f('ck_vital_signs_news2_range')),
    sa.CheckConstraint('respiratory_rate BETWEEN 0 AND 80', name=op.f('ck_vital_signs_rr_range')),
    sa.CheckConstraint('spo2 BETWEEN 50 AND 100', name=op.f('ck_vital_signs_spo2_range')),
    sa.CheckConstraint('spo2_scale IN (1, 2)', name=op.f('ck_vital_signs_spo2_scale_values')),
    sa.CheckConstraint('systolic_bp BETWEEN 40 AND 300', name=op.f('ck_vital_signs_sbp_range')),
    sa.CheckConstraint('temperature BETWEEN 30 AND 45', name=op.f('ck_vital_signs_temp_range')),
    sa.ForeignKeyConstraint(['admission_id'], ['admissions.id'], name=op.f('fk_vital_signs_admission_id_admissions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_vital_signs_patient_id_patients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recorded_by_user_id'], ['users.id'], name=op.f('fk_vital_signs_recorded_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vital_signs'))
    )
    op.create_index(op.f('ix_vital_signs_admission_id'), 'vital_signs', ['admission_id'], unique=False)
    op.create_index('ix_vital_signs_patient_recorded', 'vital_signs', ['patient_id', 'recorded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_vital_signs_patient_recorded', table_name='vital_signs')
    op.drop_index(op.f('ix_vital_signs_admission_id'), table_name='vital_signs')
    op.drop_table('vital_signs')
    # ### end Alembic commands ###
